version: '3'

services:
  frontend:
    build: ./packages/frontend
    ports:
      - "3000:3000"

  backend:
    build: ./packages/backend
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: e-commerce-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
